### ISSUE TITLE
Wont install latest update

### ISSUE THREAD

**Issue by stuCONNERS1983** [ich777/docker-xlink-kai-evolution#2]
---Starting XLink Kai---
XLink Kai v7.4.37 build 539579346 Linux x86_64 (c) 2020 Team XLink  https://www.teamxlink.co.uk/
Config file: /xlinkkaievolution/kaiengine.conf
Web interface is ready, connect to: http://127.0.0.1:34522/
Downloading language file en.xml
Initializing XLink Kai engine...
Downloading configuration... OK
Upgrade Available: A new version of XLink Kai is available.
cdn.teamxlink.co.uk/binary/kaiEngine-7.4.39-539601671.headless.debian.x86_64.tar.gz
Updating webui
Kai Engine: The engine has started
webui downloaded
webui verified OK

Seems to be stuck on version .37 when .39 is available

**Comment by ich777** [comment]
I will look into it ASAP and report back!
Please give me one day.

**Comment by ich777** [comment]
@stuCONNERS1983 this is because the query site hasn't been updated: [Click](https://www.teamxlink.co.uk/api/versionQuery.php)

It's still on version 37 and not on 39 I will conact the dev (@CrunchByte) on this.

**Comment by ich777** [comment]
@stuCONNERS1983 Is this issue preventing you from connecting to XlinkKai?
I'm already in touch with the developer and he will give me another API where I can check the actual version of XlinkKai but I think this will take a few days... :)

**Comment by stuCONNERS1983** [comment]
No. I played last night running version. 37. I had managed to update to version .38 previously. A fresh install stays at .37.

**Comment by ich777** [comment]
I hope that @CrunchByte responds quick and give me the details of the new API so that I can implement that into the Container.

**Comment by sgtlegend** [comment]
Hi there, I'll be looking to getting a new version of the releases API implemented by the end of weekend/early next week. I'll update when it is ready 😄.

**Comment by sgtlegend** [comment]
I have built a new version of the API that will remain up to date for each new release. By default it will list all platforms with grouped releases or you can pass a specific platform (macos, win32, linux) to get a more specific subset.

https://teamxlink.co.uk/api/v1/releases/legacy
https://teamxlink.co.uk/api/v1/releases/legacy?platform=linux

**Comment by ich777** [comment]
Thank you, I hope I can integrate that by tomorrow evening into the container.

**Comment by ich777** [comment]
New URL's now integrated and container is rebuilt, please force a updated of the Container and it will pick up the latest version and will install it.

**Comment by stuCONNERS1983** [comment]
This doesnt work now. Used same details to build container.

---Checking if UID: 99 matches user---
---Checking if GID: 100 matches user---
---Setting umask to 022---
---Checking for optional scripts---
---No optional script found, continuing---
---Starting...---
---Checking if XLink Kai is installed and up-to-date---
---XLink Kai not installed, downloading---
kaiengine.tar.gz        [<=>                 ]       0  --.-KB/s               
kaiengine.tar.gz        [ <=>                ]   6.18K  --.-KB/s    in 0s      
---Successfully downloaded XLink Kai---
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
---Checking if 'kaiengine.conf' is present---
---Configuration file not found, creating---
/opt/scripts/start-server.sh: line 59: /xlinkkaievolution/kaiengine: No such file or directory
---Can't create 'kaiengine.conf' putting server into sleep mode---

Rebuilt the container and errors out.

**Comment by ich777** [comment]
@stuCONNERS1983 Yes, that's actually because the link doesn't work

@sgtlegend The link to the binary doesn't work: https://cdn.teamxlink.co.uk/binary/kaiEngine-7.4.39-539601671.headless.debian.x86_64.tar.gz

![grafik](https://user-images.githubusercontent.com/28066518/105612281-5fa74f80-5dbb-11eb-8072-e1113efd3996.png)

**Comment by ich777** [comment]
@stuCONNERS1983 Did a quick workaround for this until the links of the CDN work, please update the container once more and it will download the version 7.4.39, will release a proper fix tomorrow when the links all are working. :)

**Comment by stuCONNERS1983** [comment]
Thanks, running .39 now

**Comment by CrunchBite** [comment]
@ich777 404ing links have now been replaced!

**Comment by ich777** [comment]
Thank you @CrunchBite 

Fix is now release.

Also armhf and arm64 containers are now available but I have to test them first (will be later that day):
https://hub.docker.com/r/ich777/xlinkkaievolution/tags?page=1&ordering=last_updated

**Comment by stuCONNERS1983** [comment]
Works great, Thank-you.
