### ISSUE TITLE
New update not installing

### ISSUE THREAD

**Issue by stuCONNERS1983** [ich777/docker-xlink-kai-evolution#3]
Downloading stage two configuration
Orbital Sync Established: Team XLink Europe
Session terminated, killing shell...'---Checking if UID: 99 matches user---
usermod: no changes
---Checking if GID: 100 matches user---
usermod: no changes
---Setting umask to 022---
---Checking for optional scripts---
---No optional script found, continuing---
---Starting...---
parse error: Invalid numeric literal at line 1, column 10
parse error: Invalid numeric literal at line 1, column 10
---Checking if XLink Kai is installed and up-to-date---
---'kaiengine' found but can't get download URL, continuning...---
---Checking if 'kaiengine.conf' is present---
---Setting interface to: eth0---
---Setting UDP Port to: 30000---
---Preparing Server---
---Checking for old logs---
---Starting XLink Kai---
XLink Kai v7.4.39 build 539601671 Linux x86_64 (c) 2020 Team XLink  https://www.teamxlink.co.uk/
Config file: /xlinkkaievolution/kaiengine.conf
Downloading language file en.xml
Initializing XLink Kai engine...
Downloading configuration OK
Upgrade Available: A new version of XLink Kai is available.
cdn.teamxlink.co.uk/kai/kaiEngine-7.4.40-539601682.headless.debian.x86_64.tar.gz
Kai Engine: The engine has started

**Comment by ich777** [comment]
@stuCONNERS1983 Thank you for the report, will look into this tomorrow and report back.

**Comment by ich777** [comment]
@stuCONNERS1983 seems like there is a problem with the database.

**Comment by stuCONNERS1983** [comment]
Mine updated to version 7.4.40 but version 41 then came out.

**Comment by ich777** [comment]
@stuCONNERS1983 will contact the developer again. I close this for now since there is nothing I can do about it when the API doesn't have the right version.
